version: '3'

services:
  ai-stock-api:
    image: ghcr.io/hestudy/ai-stock-api:latest
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - TUSHARE_TOKEN=${TUSHARE_TOKEN}
    volumes:
      - ./data:/app/.data
